### ISSUE TITLE
Traditional Build not opening Sumatra [Win10]

### ISSUE THREAD

**Issue by NianiaM** [SublimeText/LaTeXTools#666] opened 2016-03-09 00:56 UTC
Hi there,

I am having a few issues with LatexTools opening Sumatra on Windows 10 + MikTex. When compiling using the traditional build ('Ctrl + B') my document compiles fine, but Sumatra won't open.

My PATH and inverse search settings were definitely correct as I could type 'sumatrapdf' into the windows cmd.exe to open sumatra and use 'Ctrl + L, j' to run 'jumpToPdf.py' just fine.

Weirdly though, using 'Ctrl + L, v' to run 'viewPDF.py' did not work (giving me the error "Cannot Launch Viewer. Make sure it's in your PATH"). So I had a look at viewPDF.py and edited Line 52 from:

`su_binary = prefs_win.get("sumatra", "SumatraPDF.exe")`

to 

`su_binary = prefs_win.get("SumatraPDF", "SumatraPDF.exe")`
(based on an educated guess that there was 'SumatraPDF' in the default 'LatexTools.sublime-settings')

OR

`su_binary = prefs_win.get("sumatra", "SumatraPDF.exe") or 'SumatraPDF.exe'`
(Copying the syntax in 'jumpToPDF.py')

Both of these changes meant that 'viewPDF.py' ran fine. However, Sumatra still will not open when using 'Ctrl + B'.

The console log after hitting 'Ctrl +B' is (minus the <> to avoid quote confusion):

> module 'traditionalBuilder' from 'C:\\Users\\Name\\AppData\\Roaming\\Sublime Text 3\\Packages\\LaTeXTools\\builders\\traditionalBuilder.py'
class 'traditionalBuilder.TraditionalBuilder'
3
Welcome to thread Thread-4
['texify', '-b', '-p', '--engine=pdftex', '--tex-option="--synctex=1"', 'MNThesis.tex']
Package Control: No updated packages
Finished normally
1

Every setting is at default. What am I missing?

Thanks!

**Comment by ig0774** [comment] 2016-03-09 04:35
There are essentially two circumstances under which the builder will not launch the document on a build:

1. There are errors indicated in the log file.

1. The log file itself does not exist or cannot be opened to be read.

What you don't show is the output from the build itself which, in this case, might be the most useful thing in determining why the pdf doesn't get opened.

(PS the setting should be called "sumatra"; there's no "SumatraPDF" setting which is, oddly, why that works. The problem is that the default value of "sumatra" returns "" and using that as an executable doesn't work, hence the code in `jumpToPDF.py`. Thanks for pointing this out. It will be addressed in the next release. Unfortunately, the behaviour of the view command is completely unrelated to your other problem.)

**Comment by NianiaM** [comment] 2016-03-09 16:38
Sorry to be dense, but where can I find the output from the build?

**Comment by ig0774** [comment] 2016-03-09 17:19
It's the panel that pops up at the bottom when you do a build. It should have something like "Traditional Builder..." In it.

**Comment by NianiaM** [comment] 2016-03-09 17:35
Found it... feel dumb now. There was a package clash causing it not to build. I've come from a different editor which had colour coding on the error/warning messages.

```
TraditionalBuilder: Engine: pdflatex. Invoking texify... done.

Errors:

Thesis.tex:19: LaTeX Error: Option clash for package hyperref. []
```

Well, at least one useful thing came from this regarding the sumatra thing.

**Closed** 2016-03-12 10:40 UTC
