### ISSUE TITLE
Cite autocomplete steals caption brace

### ISSUE THREAD

**Issue by KamphuisAlex** [SublimeText/LaTeXTools#766] opened 2016-07-09 07:16 UTC
When using the autocomplete when typing \cite{} command inside a \caption{}, cite autocompletion steals the caption's brace.

example:
One types figure, and uses ctrl+l, e to begin an environment. Then one inserts a graphic (or table, etc.) and starts writing \cap..  and use autocomplete to end up with (where the cursor is at the HERE):
```
\begin{figure}
\includegraphics{x.jpg}
\caption{HERE}
\end{figure}
```
Then one could type a caption:
`This picture was published originally by me in \cite{`
and use the autocomplete there to select the reference needed.

The result will be (with cursor at HERE)
```
\begin{figure}
\includegraphics{x.jpg}
\caption{This picture was published originally by me in \cite{thereference}HERE
\end{figure}
```
and so the cite autocompletion has eaten the closing bracket of `\caption{}`

Manually typing (so with autocompletion disabled) `\cite{thereference}` would open a new set of braces when you type `\cite{` and cause no trouble with the closing caption brace.

**Comment by r-stein** [comment] 2016-07-09 09:16
"It's not a bug, it's a feature"

Currently `cite`/`ref`/`input` try to be smart and only add a closing brace if it does not exists. This is also added when you trigger it using the keybinding `C-x, C-f` or the autocompletion.
If you cancel the cite dialog the closing brace is not added.

I personally think it would be better to only add the closing brace if it was triggered via `{` and `setting.auto_match_enabled` is true. However also add it after the dialog was canceled. This would resolve the issue and (at least in my opionion) be more intuitive.

Nonetheless we should have the same behavior for all fillall commands (`ref`, `cite`, `input`, `include`, ...)

**Comment by msiniscalchi** [comment] 2016-07-09 10:24
There is also a setting that controls that (for ref/cite). Please take a
look at the relevant section in the README file.

On Sat, Jul 9, 2016 at 11:16 AM, Richard Stein <notifications@github.com>
wrote:

> "It's not a bug, it's a feature"
>
> Currently cite/ref/input try to be smart and only add a closing brace if
> it does not exists. This is also added when you trigger it using the
> keybinding C-x, C-f or the autocompletion.
> If you cancel the cite dialog the closing brace is not added.
>
> I personally think it would be better to only add the closing brace if it
> was triggered via { and setting.auto_match_enabled is true. However also
> add it after the dialog was canceled. This would resolve the issue and (at
> least in my opionion) be more intuitive.
>
> Nonetheless we should have the same behavior for all fillall commands (ref,
> cite, input, include, ...)
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/SublimeText/LaTeXTools/issues/766#issuecomment-231524959>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAo1BUzpTMwnXeokzSGBF2eaG6sNfNHXks5qT2b8gaJpZM4JIkCM>
> .
>



-- 
Marciano Siniscalchi
Economics Department, Northwestern University
http://faculty.wcas.northwestern.edu/~msi661

**Comment by KamphuisAlex** [comment] 2016-07-09 11:16
@r-stein I agree, I think that is indeed more intuitive.
@msiniscalchi I think you mean you can turn off the auto trigger upon typing `\cite`, and enable `auto_match_enabled` ? In this case you could indeed type `\cite{` , which would then result in `\cite{HERE}` with the cursor at HERE. Then you could `c-l,c-f`. Although this behaviour works, the solution is based on omitting the autotrigger 'smartness' (described by r-stein above) about deciding whether to put a bracket and letting ST do it in stead. Indeed ST's solution works more intuitive in my opinion but this requires more keystrokes.

**Comment by msiniscalchi** [comment] 2016-07-09 11:21
​Er... sorry, my bad. What I meant is the ​"ref_add_parenthesis" setting,
which is only documented in the settings file (we need to fix this). Here's
the relevant text:

// Sometimes a \ref is preceded by an open parenthesis.
// By default, we do not close the parenthesis after completion
// But, if you want us to, set this to true.
"ref_add_parenthesis": false,

So you can try setting "ref_add_parenthesis" to true and see if it helps.
Maybe not.

**Comment by msiniscalchi** [comment] 2016-07-09 11:24
​
​Sorry, I reread your question now----I don't think that option will help.
Or, rather, it may help, but it will likely have
​other ill side-effects. Basically, this is a bad interaction between ST's
brace autocompletion and Latextools' citation code. It irks me, as well.

**Comment by KamphuisAlex** [comment] 2016-07-09 17:33
I can confirm, that option does not help.

**Closed** 2016-08-04 17:32 UTC
Labels: enhancement
