### ISSUE TITLE
Support for the Biblatex cite commands that do not begin with \cite

### ISSUE THREAD

**Issue by jahaller** [SublimeText/LaTeXTools#178] opened 2013-05-16 14:56 UTC
Hi,

as far as I can see, several Biblatex commands such as `\textcite` are not supported in Latextools at the moment. Specifically, typing `\textcite` only results in my overly eager autocompletion changing it into `\text\cite{`(as long as I have `"auto_complete_selector": "text"` turned on.) If I then manually change it back into `\textcite{}` and try to obtain the dropdown menu for bibliography entries, I get an error: `Ref/cite: unrecognized format.`

It seems that the same issue also affects all other Biblatex citation commands that do not start with `\cite`: `\parencite`, `\footcite` `\smartcite`, `\supercite`, `\autocite`, `\fullcite`, `\footfullcite`, `volcite`, `\notecite`, and variants thereof.

Thanks for your help!

**Comment by dofine** [comment] 2015-05-06 07:16
+1.
Now using LaTeXing which works with \autocite, but the cite panel is incomplete somehow. Can't get the citation that I need.

**Comment by msiniscalchi** [comment] 2015-05-06 13:06
Please be patient... I'm doing my best to work through all requests and
todos...

**Comment by bnicenboim** [comment] 2015-05-26 13:35
Hi, did someone  manage to do a hack and be able to use the *cite commands of biblatex? I checked Novares's code of https://github.com/Norvares/LaTeXTools/blob/master/latex_cite_completions.py and I didn't find what was the difference...

I guess this:
NEW_STYLE_CITE_REGEX = re.compile(r"([^{},]*)(?:,[^{},]*)*\{(?:\].*?\[){0,2}([a-zX*]*?)etic\\")

has to be changed, but I can't figure out this amount of regex....

anyone?

**Comment by ig0774** [comment] 2015-05-26 14:11
@bnicenboim: Norvares at [line 28 of `latex_cite_completions.py`](https://github.com/Norvares/LaTeXTools/blob/master/latex_cite_completions.py#L28) changes `NEW_STYLE_CITE_REGEX` to `NEW_STYLE_CITE_REGEX = re.compile(r"([^{},]*)(?:,[^{},]*)*\{(?:\].*?\[){0,2}([a-zX*]*?)etic([a-zX*]*?)\\")`. Which looks like it should work for the common ones, though you'd also need to change the keymap file(s) for autocomplete to work. 

If you want to go absolutely insane, #506 supports **everything** in biblatex as far as I can make out (and most things that look like the standard cite commands). It does work (I use it pretty much daily), but the regexes make my brain bleed. (I used [Debuggex](https://www.debuggex.com/) to come up with them...)

**Comment by bnicenboim** [comment] 2015-05-26 15:18
@ig0774  So which files would I need from your fork?
latex_cite_completions.py and latex_ref_cite_completions.py?

Thanks!

**Comment by ig0774** [comment] 2015-05-26 15:45
Either look [here](https://github.com/SublimeText/LaTeXTools/pull/506/files) or the `latex_cite_completions.py` and `Default (*YOUR OS HERE*).sublime-keymap` from my `extended_cite_command_matching` branch (my `master` branch just tracks upstream).

**Comment by bnicenboim** [comment] 2015-05-26 15:55
it didn't work :(
When I do \parencite{
I get this error: Ref/cite: unrecognized format.

**Comment by ig0774** [comment] 2015-05-26 16:19
Just to confirm, did you do something like this:

Download [this](https://raw.githubusercontent.com/ig0774/LaTeXTools/extended_cite_command_matching/latex_cite_completions.py) file and copy it, overwriting the `latex_cite_completions.py` file in your ST packages directory and then restart all instances of ST? I can't reproduce it here (i.e. `\parencite{` works for me when I do the above...)

**Comment by bnicenboim** [comment] 2015-05-26 16:24
ok, it's working now, I must have broken something when I added the support for Rnw files....
I copied the file again, and it's working like a charm :)
thanks!!

**Comment by msiniscalchi** [comment] 2015-12-10 04:35
Closing as it's solved by #506 (which we will merge at some point soon, I hope).

**Comment by ig0774** [comment] 2016-04-19 11:12
#506 has been merged...

**Closed by ig0774** 2016-04-19 11:12 UTC
