### ISSUE TITLE
Feature Request: Display citing paper info when mouse or cursor over the citation item

### ISSUE THREAD

**Issue by clsmt** [SublimeText/LaTeXTools#1334] opened 2018-06-02 19:04 UTC
Is it possible to automatically display the citation paper info (title, authors, etc.) when we move the cursor or mouse over the `\cite{abc123}` in the text? 

This feature would be very helpful when we are revising the papers. Citation key means nothing (as it shouldn't) to us humans writing the paper, and we are not supposed to remember which paper is which citation key.

**Comment by r-stein** [comment] 2018-06-03 11:27
This is a duplicate of your own issue #1328

**Closed by r-stein** 2018-06-03 11:27 UTC
Labels: duplicate

**Comment by clsmt** [comment] 2018-06-03 16:54
Oh Sorry I totally forgot about it.
