### ISSUE TITLE
evince backwards search no longer works with spaces in filename

### ISSUE THREAD

**Issue by darthoctopus** [SublimeText/LaTeXTools#841] opened 2016-09-16 01:18 UTC
when the filename contains spaces, the function `on_sync_source` (from `evince_backwards_search`) is for some reason not being called on GNOME 3.20 (this used to work on 3.18).

This can be fixed by changing line 194 from

    'file://' + quote(pdf_file, "/$+!*'(),"),

to

    'file://' + quote(pdf_file, "/$+!*'(), "),

(i.e. by adding space to the list of characters escaped. while you're at it you could add more characters, a la <https://www.benwhale.com/blog/synctex-gedit-evince/>)

**Comment by darthoctopus** [comment] 2016-09-16 01:36
interestingly, forward search still works, so I guess the real problem is an evince dbus API change (or some other internal wrangling)

**Comment by ig0774** [comment] 2016-09-16 22:57
I think the actual problem was introduced by 2f861d0, in particular, in [line 97](https://github.com/SublimeText/LaTeXTools/blob/2f861d08c7801ca7dfec40524417a63a6733625a/evince/evince_backward_search#L97), where it compares `unquote(uri)` to `self.uri`. This obviously was intended to compare two *unquoted* URIs to match regardless of which characters were encoded (the alternative is to unquote and then quote with a known schema, but that seems like more effort than is necessary). Forward sync is (somewhat) unaffected because it doesn't have this same logic error.

You're probably right about adding additional characters to the "safe_chars" setting, but I'd want to be cautious about what characters we're adding. In particular, square brackets (`[]`) work for me despite being encoded whereas `@` does not... It would be nice if there were some way to determine which characters can safely be allowed unescaped, but maybe trial and error is the only way.

**Comment by ig0774** [comment] 2016-09-20 11:08
The issue with spaces has been fixed in v3.11.0. I've also added the various characters I could determine didn't need to be escaped, which should make it compatible with a greater range of file names. Thanks for the bug report and digging into the issue!

**Closed by ig0774** 2016-09-20 11:08 UTC
Labels: bug
