### ISSUE TITLE
Math preview not working

### ISSUE THREAD

**Issue by RomanKarwacik** [SublimeText/LaTeXTools#883] opened 2016-10-30 15:16 UTC
Windows 10 64bit
LaTeXTools v3.12.0 (2016-10-30)
Sublime Text Build 3126 64bit
TexLive 2016
ImageMagick 7.0.3-4 Q16 x64 2016-10-10
GPL GhostScript 9.20

Every math preview results in a questionmark:
![previewnotworking](https://cloud.githubusercontent.com/assets/8593000/19837555/671ee0c4-9ebc-11e6-98a5-b4958296ce3f.PNG)

I've got ImageMagick and Ghostscript in $PATH$. There is no error output in the console.

**Comment by 2sls** [comment] 2016-10-30 15:24
I'm observing same issue of question mark in box where I presume the preview is supposed to be render.

**Comment by r-stein** [comment] 2016-10-30 15:36
- Does the image preview previews pdf images?
- Can you open the folder `%AppData%\..\Local\Sublime Text 3\Cache\LaTeXTools\preview_math` and check whether the images were generated?

**Comment by RomanKarwacik** [comment] 2016-10-30 15:42
@r-stein pdf's work fine, in the cache folder are only the tex files for a split second, no images.

**Comment by 2sls** [comment] 2016-10-30 15:47
I don't see anything in the cache folder.

I never used the image preview feature. Don't know if my code is too customized but I don't see the "show" "hide" "open image" "open folder" links in my editor.

**Comment by RomanKarwacik** [comment] 2016-10-30 15:48
@2sls Do you have ImageMagic and Ghostscript installed? You didn't list them.

**Comment by r-stein** [comment] 2016-10-30 15:52
@RomanKarwacik you could comment [this loop](https://github.com/SublimeText/LaTeXTools/blob/v3.12.0/st_preview/preview_math.py#L140), restart ST, and verify that you can  compile the document via pdflatex and convert it via convert.
Unfortunatly I don't have debug print statements, because it would be to much output.

@2sls You are also using Windows 10?

**Comment by RomanKarwacik** [comment] 2016-10-30 15:58
I figured it out, you need to have your texlive distribution in your PATH, it doesn't use the ones from LatexTools properties. Would be great if I could specify the paths in the properties file, but for now it's working!
![previewworking](https://cloud.githubusercontent.com/assets/8593000/19837804/fed757de-9ec1-11e6-9c82-8fc857d0863a.PNG)

**Comment by 2sls** [comment] 2016-10-30 16:42
@RomanKarwacik  I didn't know that was required. Is ImagicMagick a package control plugin or some standalone? I know Ghostscript is standalone. I think I already have Miktex in my PATH so not sure still what's missing.


@RomanKarwacik I'm on Win7

**Comment by RomanKarwacik** [comment] 2016-10-30 16:45
ImageMagic is a standalone software:

> Those functionalities rely on [ImageMagick](http://www.imagemagick.org) to be installed and in your PATH.

**Comment by 2sls** [comment] 2016-10-30 17:09
@RomanKarwacik I got the preview image to work with paths to imagemagick and ghost script. 

But math preview still question mark?

**Comment by RomanKarwacik** [comment] 2016-10-30 17:12
Could you post your PATH?

**Comment by 2sls** [comment] 2016-10-30 17:15
OK i tried a different project and .PNG is rendered successfully inside the editor.  My prior failure was with .EPS - I've been using epstopdf package.

The relevant paths are:
C:\Program Files\ImageMagick-7.0.3-Q16;C:\Windows\system32;C:\Program Files\MiKTeX 2.9\miktex\bin\x64\;C:\Program Files (x86)\SumatraPDF;C:\Program Files\gs\gs9.20\bin

**Comment by r-stein** [comment] 2016-10-30 21:15
@2sls The image preview does also work for pdf and eps files by generating a thumbnail via ImageMagick as the image preview does. I may just add a setting to read the programs instead of assuming them to be in the path.

**Comment by 2sls** [comment] 2016-10-31 01:03
so I guess this is likely not to be a bug but a mis-config between imagemagick and ghostscript. apparently it doesn't see gs ... dunno how paths are wrong since I can call ghostscript from command prompt. 

C             vs10
COPYRIGHT      Copyright (C) 1999-2016 ImageMagick Studio LLC
DELEGATES      bzlib freetype jpeg jp2 lcms png tiff x11 xml wmf zlib
FEATURES       OpenMP
HOST           Windows
LIB_VERSION    0x703
LIB_VERSION_NUMBER 7,0,3,4
NAME           ImageMagick
RELEASE_DATE   2016-11-30
VERSION        7.0.3
WEBSITE        http://www.imagemagick.org

**Comment by FacelessJ** [comment] 2016-10-31 05:27
I get the question marks too. I've installed ImageMagick 7.03-4 Q16 and GhostScript 9.20, using MikTeX 2.9 on Windows 7 (64 bit) with ST 3126.

I can see previews for \includegraphics (.png and .pdf). I have ImageMagick root dir, GhostScript bin dir and MikTek bin dir in $PATH (can call convert test.pdf test.png, pdflatex and gswin32/c on command line). texpath in settings is set to "$PATH".

If I set preview_math_mode to all, I can occassionally see .tex files in preview_math directory. Sometimes they hang around, sometimes not. If they do, I can open the .tex file, compile it with pdflatex and then convert it using ImageMagick. If I then go back to ST3, that equation now shows live-preview.

Not seeing any errors in the console either.

Have tried multiple .tex files (including the cached .tex file that preview produces). Only time I can see the math preview is if I manually build the .png (Can then see it in the cached .tex file and the original .tex file).

Lastly, for image preview, I only see "(Open Image)" and "(Open Folder)", no "(Show)" or "(Hide)". Not sure if that is indicative of anything.

**Comment by r-stein** [comment] 2016-10-31 08:24
>Lastly, for image preview, I only see "(Open Image)" and "(Open Folder)", no "(Show)" or "(Hide)". Not sure if that is indicative of anything.

This is visible if you use phantoms (select/all) in [preview_image_mode](https://github.com/SublimeText/LaTeXTools#preview-image-settings)

> Edit Figured it out. I have sublime installed on F: drive rather than C:. As such, pdflatex can't find the .tex file in the cache on the C: drive. Just need to add "C: && " to the start of the command string in preview_math.py, Line 113 and then live preview works.
>
>I've modified my preview_math.py file to get the drive name using temp_drive, _ = os.path.splitdrive(temp_path) and then passing that to the command string, however, not really well versed in python, so not sure if that's a cross-platform solution.

Actually we are using the folder returned by the command `sublime.cache_path()` so the drive should be irrelevant. However I don't know how that change fixes something.

**Comment by r-stein** [comment] 2016-10-31 08:26
@2sls can you try to convert a pdf file in the cmd via `convert test.pdf test.png` and check, that it succeds.

**Comment by FacelessJ** [comment] 2016-10-31 08:46
@r-stein 

> This is visible if you use phantoms (select/all) in preview_image_mode

Yeah, that's what I meant. I see a phantom with the image, but only the "Open" links appear, but not the "Show/Hide" links. It's no big deal.

> so the drive should be irrelevant

Drives on windows maintain their own working directories. If I call `cd C:\Users\...\LaTeXTools\preview_math" && pdflatex -interaction=nonstopmode foo.tex` from a shell that looking at C:, then it works, but if I change it to F:, then run the same command (i.e since sublime is installed on my F:, thus any commands are local to F:, not C:), pdflatex complains saying "! I can't find file  'foo.tex'". Setting it to C: first is what fixes the issue

**Comment by r-stein** [comment] 2016-10-31 08:59
>> This is visible if you use phantoms (select/all) in preview_image_mode
>
>Yeah, that's what I meant. I see a phantom with the image, but only the "Open" links appear, but not the "Show/Hide" links. It's no big deal.

This sound as you are using the (default) hover popup, which does not have show/hide, because it only appears if you want to it have anyway. The phantoms are used to show `all` images at once. The `selected` option was only added, because it is not a big deal and it is in the math preview.

>> so the drive should be irrelevant
>
>Drives on windows maintain their own working directories. If I call `cd C:\Users\...\LaTeXTools\preview_math" && pdflatex -interaction=nonstopmode foo.tex` from a shell that looking at C:, then it works, but if I change it to F:, then run the same command (i.e since sublime is installed on my F:, thus any commands are local to F:, not C:), pdflatex complains saying "! I can't find file  'foo.tex'". Setting it to C: first is what fixes the issue

A thanks good to know =). You could try the version, which is in the git on the master branch.  Since @ig0774 has improved that part to work together with https://github.com/SublimeText/LaTeXTools/pull/673.

**Comment by 2sls** [comment] 2016-10-31 16:57
@r-stein 
I did 'magick test.pdf test.png' and it did convert correctly...
but my delegates don't show pdf so I don't know how that's possible.

**Comment by Gormador** [comment] 2016-10-31 17:13
Hey guys!

Seeing as I just spent two hours trying to fix a seemingly broken preview (spoiler alert: my setup was the issue, not LaTeXTools ;-) ), if sharing what worked for me helps others it won't be wasted time!

So, **on Windows 10, ST3, MiKTeX**, if after installing ImageMagick and Ghostscript as well as making sure all of those are in your _PATH_ and that _%path%_ is in your `texpath`, the preview doesn't work and you are unable to call the `convert foo.pdf foo.png` (foo.pdf being your test pdf of choice and foo.png the expected output's name) command line, try reinstalling ImageMagick but this time, check the "Install legacy utilities (e.g. convert)" option during the install process...

![Select "Install legacy utilities (e.g. convert)"](https://puu.sh/s1TJu/a8f1013f9f.png)

Hope this helps :)

(Also @r-stein , maybe specifying the importance of the `convert` command in the readme would be wise! Allow me to also cease the opportunity to thank you for your contributions to the project ;-) )

**Comment by r-stein** [comment] 2016-10-31 17:36
@Gormador thanks for that hint, I have added it to the README.

**Comment by 2sls** [comment] 2016-10-31 18:28
@Gormador yes this was the problem!

**Comment by Joshua1989** [comment] 2016-11-01 03:40
Hey, I am using MacOS 10.12.1, I just installed GhostScript 9.20 and ImageMagick 6.9.3, and add them into $PATH, and in the "texpath" I have $PATH in it.
I tried to use "convert" in the command line and it works.
But when I include figures or write equation, nothing happens.

So I think I must miss some parts. Can you help me figure this out.

**Comment by r-stein** [comment] 2016-11-01 08:49
@Joshua1989 I have releases a new version `v3.12.1`, which might fix that isse. Otherwise run `LaTeXTools: Check System` (which is also added with the release) from the command panel (`C-shift-p`) to get a hint what is missing.

**Comment by Joshua1989** [comment] 2016-11-01 13:03
<img width="1288" alt="screenshot 2016-11-01 09 01 13" src="https://cloud.githubusercontent.com/assets/1357342/19890559/e8234024-a011-11e6-8ceb-349677077689.png">
Seems that everything is available

**Comment by irfus** [comment] 2016-11-01 13:10
As @Joshua1989, using ST3 on MacOS 10.12.1, I can see previews of png images, but the popup only shows "Preparing image for preview..." for a pdf. `LaTeXTools: Check System` shows status 'available' for all required programs. `convert image.pdf image.png` works correctly on the command-line as well.

**Comment by ig0774** [comment] 2016-11-01 14:38
@Joshua1989 and @irfus: A bug was inadvertently introduced in 3.12.1 that broke the preview for PDF, EPS, etc. This should be fixed in 3.12.3.

@Joshua1989: When you get 3.12.3 could you check if equations are still failing? If they are, could you post the contents of your Sublime console (**View > Show Console**). That may have some valuable clue to what's broken.

**Comment by Joshua1989** [comment] 2016-11-01 16:44
<img width="1436" alt="screenshot 2016-11-01 12 40 14" src="https://cloud.githubusercontent.com/assets/1357342/19897916/630c5730-a030-11e6-9aca-c6591b455681.png">
@ig0774 : Both image and equation are still failing, here is the picture of what console gave me. It seems nothing was done when I edit figure and equation. I think if it works there should be some small tex files compiled on the background and print log to console, but it didn't.

**Comment by r-stein** [comment] 2016-11-01 16:55
@Joshua1989 Do you use the LaTeX syntax shipped with ST or have you overwritten it with an other syntax? Both functions rely on the scope definitions of the new syntax.

**Comment by Joshua1989** [comment] 2016-11-01 17:15
@r-stein : I just added IEEEeqnarray as math environment for the LaTeX syntex so that code inside IEEEeqnarray are highlighted, does that matters?

**Comment by ig0774** [comment] 2016-11-01 17:18
Where did you save your modified syntax file? Unfortunately, the phantoms will only work if the syntax file is named `Packages/LaTeX/LaTeX.sublime-syntax`.

**Comment by Joshua1989** [comment] 2016-11-01 17:25
@ig0774 : I just edit the original file, so the file name is not a problem. I also have a preamble including all the customized latex macros, but since in the above picture I didn't use any of them, I think that should not be the problem.
I also start with a clean tex document, but phantoms still fails to work.

So let me clarify what I have done:

1. Install GhostScript and ImageMagick
2. Add them into $PATH and check "convert" command works
3. Use "Check system" in LaTeXtools to see what is missing

Is that all I need to do to make math live work in ST3126?

**Comment by ig0774** [comment] 2016-11-01 17:35
Just to confirm things are setup properly:

1. In the ST console with the TeX document open, run `view.settings().get('syntax')`. What's the output there?
1. Move the cursor inside the equation (i.e., somewhere between the `\[` and the `\]`) then open the console and type `view.scope_name(view.sel()[0].a)`. That will give you the scope of the equation.

With both of those pieces of information we should be able to tell if things should work...

**Comment by Joshua1989** [comment] 2016-11-01 17:39
<img width="871" alt="screenshot 2016-11-01 13 38 27" src="https://cloud.githubusercontent.com/assets/1357342/19900027/802440e6-a038-11e6-9021-b25e09877135.png">
Here is the output from console

**Comment by ig0774** [comment] 2016-11-01 17:40
Incidentally, on the other issues reported on this thread:

* v3.12.3 supports running the `magick` without needing to install the "legacy" `convert` script (this applies to ImageMagick v7.x... for v6.x `convert` is obviously still needed)
* The `texpath` setting is now honoured
* On Windows, things should work correctly where ST is installed on a non-C: drive. Note, however, that installing ST on a non-mapped network drive is not currently supported (this is a limitation of `cmd.exe`)

**Comment by ig0774** [comment] 2016-11-01 17:49
@Joshua1989: From the scopes, looks like your custom syntax corresponds to an earlier version of the syntax. In particular, equation phantoms are only generated if the equation uses a scope under `meta.environment.math`. Similarly for image support `\includegraphics{}` needs to be mapped to the `meta.function.includegraphics.latex` scope. The LaTeX syntax underwent a major revision with ST build 3119. If you can update your modified syntax to match that version, things should work.

**Comment by r-stein** [comment] 2016-11-01 17:58
@Joshua1989 I recommend to take the latest syntax and add that environment there. Modifiing the scope names might fail, because the scope ranges are assumed to be like in the new syntax and if it would extract the wrong content if they differ.

**Comment by Joshua1989** [comment] 2016-11-01 18:12
@r-stein and @ig0774 : The older version of latex syntax is the problem! It works now.
In the picture below you can see the equation pops up but is incorrect.
The only thing left I can explore on myself is try to add customized preamble for it.
Also, the figure preview does not show the original figure, it is much darker, I guess this is because I modified the theme and somehow it affects the figure preview.
<img width="1242" alt="screenshot 2016-11-01 14 09 04" src="https://cloud.githubusercontent.com/assets/1357342/19901226/c933345a-a03c-11e6-9f48-07f2200d782e.png">

**Comment by irfus** [comment] 2016-11-01 18:29
Can confirm both equation and graphics previewing works in the latest release. However, selecting an equation, while successfully generating a preview, spams console with `mdpopups: Failed to convert/retrieve scheme to CSS!`. 

<img width="648" alt="screen shot 2016-11-01 at 23 56 14" src="https://cloud.githubusercontent.com/assets/487995/19901996/22d5f2b6-a08f-11e6-9b45-97262b9514d5.png">

**Comment by ig0774** [comment] 2016-11-01 18:38
@irfus: What color scheme are you using? Its probably related to that. I can't reproduce it here.

**Comment by irfus** [comment] 2016-11-01 18:43
Color scheme is the culprit, you're right. I'm using the One Dark scheme, changing it fixed the issue.

Thanks guys! The live previewing is a neat feature :-)

**Comment by r-stein** [comment] 2016-11-01 19:54
@irfus We use mdpopups to retrieve the default color from the colorscheme. If this fails we fallback to an other color. You can also set it in [the settings file](https://github.com/SublimeText/LaTeXTools/blob/v3.12.3/LaTeXTools.sublime-settings#L111). This should avoid that warning without changing the color scheme.

**Comment by r-stein** [comment] 2016-11-01 19:56
@Joshua1989 you have an image with an transparent background so it is set to the dark popup background. It may be the best if we change background behind the image to white for any scheme.

**Comment by irfus** [comment] 2016-11-01 20:01
@r-stein Thanks for the explanation and the pointer to the relevant setting.

**Comment by GerjanOnline** [comment] 2016-11-04 14:54
I still have this issue. My system check:

```
gswin32c   C:\Program Files (x86)\gs\gs9.20\bin\gswin32c.exe                available  GPL Ghostscript 9.20 (2016-09-26)
magick     C:\Program Files\ImageMagick-7.0.3-Q16\magick.exe                available  ImageMagick 7.0.3-5 Q16 x64 2016-10-31 http://www.imagemagick.org
```

However, when I have my cursor in a math equation I get:
```Failed to run 'pdflatex' to create pdf to preview.```

My `Cache\LaTeXTools\preview_math` is filled with `.err` files with the error message above

**Comment by LaithAlwahaidi** [comment] 2016-11-04 19:47
I'm also still having the same issue as above. Image preview works fine, but not equation preview

**Comment by Joshua1989** [comment] 2016-11-04 20:57
@GerjanOnline and @LaithAlwahaidi : I guess it is possible that the command `pdflatex` is not in environment variable `PATH`, try typing
`pdflatex foo.tex`
to see whether you can compile the LaTeX source file from command line.

If not, add your latex path to `PATH` and see whether the problem still exists

**Comment by ig0774** [comment] 2016-11-04 21:00
@GerjanOnline: Can you give an example of an equation you are trying to view that doesn't work?

**Comment by GerjanOnline** [comment] 2016-11-04 21:25
@ig0774 even a very simple one like `$\Pi$` does not work:

`ERROR: Failed to run 'pdflatex' to create pdf to preview.`

In console I only see:
`Running "pdflatex -interaction=nonstopmode e57754e729eb7c85d66e080ab7528447.tex"`

**Comment by GerjanOnline** [comment] 2016-11-05 08:38
Problem solved for me: https://github.com/SublimeText/LaTeXTools/issues/920#issuecomment-258598688 :+1:

**Closed** 2017-01-09 14:19 UTC
