### ISSUE TITLE
No bib files found!??

### ISSUE THREAD

**Issue by striatum** [SublimeText/LaTeXTools#228] opened 2013-07-10 11:54 UTC
Hi!
I am bit of a newbie in Mac, Sublime, LaTeXTools, so, please, bear with me and help:
I am using
\documentclass[man,11pt,a4paper,apacite,floatsintext]{apa6}
and if I invoke \cite{ I am getting an automatic message that there is no bibtex file. However, it exists, and, inf fact, file compiles fine. So, I really do not get it why I am getting this annoying message?! If I use something else, like /citep{ or \citealp{, no message and all is fine. only for the most basic \cite{
My bib file is in the same directory, and I tried both
\addbibresource{data.bib}
and
\bibliography{data}

Please, help!
Many thanks,
Petar

**Comment by c7h** [comment] 2015-05-25 19:39
The Problem is due to the non-working function `get_tex_root(view)` in `getTeXRoot.py` which will return the wrong document path. You can easily fix this by defining the `TEXroot` in your settings. Use an absolute path!

**Comment by msiniscalchi** [comment] 2015-12-10 04:37
Addressed in #522 , which is already in master.

**Closed by msiniscalchi** 2015-12-10 04:37 UTC

**Comment by chaonan99** [comment] 2017-05-14 02:01
Hi all, I got the same error but case is a little different for me. Aside from a `main.tex` file in `$PROJECT_ROOT` and several `.tex`s in `$PROJECT_ROOT/chapter`, my reference files are in `$PROJECT_ROOT/ref`. I found that moving them to `$PROJECT_ROOT` and set `TEXroot` to `$PROJECT_ROOT` works but I still want to hold the folder hierachy. Is there any way to do that?

**Comment by zhenjieliang** [comment] 2017-05-14 16:37
To chaonan99 "add the following TEX-root magic comment at the top of each of your included files-ie each file in $PROJECT_ROOT/chapter"

% !TEX root = ../main.tex

problem solved.

p.s. I use sublime text as my tex editor.

**Comment by Koppeprojects** [comment] 2023-07-18 14:41
I'm happy to use the suggestions when I type \cite{  thank you for that.
But for some reason I needed put an absolute path instead of the two dots in
 % !TEX root = ../main.tex
So in my case there is something like
 % !TEX root = /Users/username/Documents/project/00_main.tex

Maybe this is worth mentioning as a tip for other users to try.
