### ISSUE TITLE
\cite autocomplete doesn't work with multiline title strings

### ISSUE THREAD

**Issue by emichael** [SublimeText/LaTeXTools#648] opened 2016-01-27 22:17 UTC
If I have a bib file that looks like this

```
@article{foobar,
  author =        {John Smith},
  journal =       {Nature},
  month =         dec,
  number =        {4},
  pages =         {1--16},
  title =         {Foo foo foo foo foo foo foo foo
                   bar bar bar},
  volume =        {10},
  year =          {2016},
}
```

typing `\cite{bar` won't offer foobar as an option.

**Comment by ig0774** [comment] 2016-02-01 16:50
I can't reproduce this using that entry on v3.6.2. Is there something else going on in your bibliography file? Is anything printing to the console? (Granted the full title doesn't show up anywhere, but I get it offered as an option, etc.).

**Comment by emichael** [comment] 2016-02-02 22:17
Sorry, I made up that example without actually testing it. Here's one that definitely works (or rather, doesn't work):

```
@article{foo,
  author =        {John Smith},
  journal =       {Nature},
  month =         dec,
  number =        {4},
  pages =         {1--16},
  title =         {Foo foo foo foo foo foo foo foo
                   bar bar bar},
  volume =        {10},
  year =          {2016},
}

@article{jsmith,
  author =        {John Smith},
  journal =       {Nature},
  month =         dec,
  number =        {4},
  pages =         {1--16},
  title =         {Foo foo foo foo foo foo foo foo
                   bar bar bar},
  volume =        {10},
  year =          {2016},
}
```

I would expect `\cite{bar` to offer both citations as options, since "bar" is in the title of both.

**Comment by ig0774** [comment] 2016-02-02 22:55
Ah yes, that does explain it. The current regex we use for parsing bibliography entries doesn't handle line breaks at all. Your original example appeared to work because `bar` showed up in *another* field used for completions, the entry key.

I'm not certain this is easily fixable, in part because [Python's re implementation doesn't support recursion](http://stackoverflow.com/a/24015118) and in part because we need to support constructs like `title = {Blah blah blah \somecommand{blah} Blah blah}`, which makes it impossible to to just capture up to the first closing bracket (which is a trade-off we usually make). 

The (somewhat) good news is that this will be fixed when #519 is merged. The bad news is that I don't know when that will be.

**Comment by emichael** [comment] 2016-02-02 23:09
Okay, makes sense. There probably is *some* reasonable hack to support multiline titles, though (e.g., just pulling in the new regex lib and using recursion). I think it would be worth it since they're fairly common. But in the long term, actually parsing bibtex files instead of trying to use regex on something that's not regular is the way to go. :-)

**Comment by ig0774** [comment] 2016-05-15 13:34
So, #519 has been merged, but it requires some action to activate the changes because they were causing some issues in some situations (in particular #519 implements a full bibtex parser which can be slow for very large files). If you want to try it out, you need to change the `bibliography` setting in your settings to `"new_bibliography"`. This should support multiline titles, but it may have some increased loading time if you have a very large bibliography.

**Closed** 2016-12-08 22:23 UTC
Labels: enhancement
