### ISSUE TITLE
Cannot type { after \cite in ST3

### ISSUE THREAD

**Issue by LucaMarconato** [SublimeText/LaTeXTools#816] opened 2016-08-16 18:46 UTC
Cannot type { after \cite in ST3.
I have to press <space> <{> <LEFTARROW> <BACKSPACE> or using a custom snippet.
Nothing more to declare but if required I am ready to give more details if needed.

NOTE: before reporting this issued I had just updated to the latest version and had restarted ST3, and I still experienced the bug.

**Comment by r-stein** [comment] 2016-08-16 18:49
Can you open the console ``ctrl+` `` and check if it logs an error when you press `{`?

**Comment by stefan-braun** [comment] 2016-08-16 20:20
Same with `\usepackage` and `\input`.
```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 568, in run_
    return self.run(edit, **args)
  File "C:\Users\User\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\latex_fill_all.py", line 1012, in run
    prefix != fancy_prefix
UnboundLocalError: local variable 'fancy_prefix' referenced before assignment
```

**Comment by stefan-braun** [comment] 2016-08-16 20:22
Possible duplicate of https://github.com/SublimeText/LaTeXTools/issues/809

**Comment by r-stein** [comment] 2016-08-16 20:57
@stefan-braun I have released a fix for that. It should be soon in Package Control.

**Comment by stefan-braun** [comment] 2016-08-17 16:58
@r-stein Thank you for the bug fix, I can confirm that the autocomplete for `\usepackage` and `\input` works fine again.

**Comment by swun90** [comment] 2016-08-19 04:49
Just upgraded. Bugs unfixed.

But with `LaTeXTools` installed or **removed**, `{` cannot be typed after `\include*`, `\input*` or `\documentclass*`. Here `*` denotes any letters.

But that's all in the syntax `LaTeX`. If setting syntax to `TeX`, then no problem!

**Comment by swun90** [comment] 2016-08-19 04:57
And a question. Did you cancel some `Tab` auto-completion? Like in a new blank file, can't even type `Tab` to auto complete `\usepackag`.

**Comment by r-stein** [comment] 2016-08-19 05:38
@swun90 have you tried to restart sublime text? In addition it would be necessary to provide the console log ``ctrl+` ``.

**Comment by swun90** [comment] 2016-08-19 06:30
Of course I restarted ST3, whether after removing or reinstall.
The console log is a little long. I don't know how much you need it. But here it is.
```
DPI scale: 1
startup, version: 3114 windows x64 channel: stable
executable: /D/Program Files/Sublime Text 3/sublime_text.exe
working dir: /D/Program Files/Sublime Text 3
packages path: /C/Users/SWUNQ/AppData/Roaming/Sublime Text 3/Packages
state path: /C/Users/SWUNQ/AppData/Roaming/Sublime Text 3/Local
zip path: /D/Program Files/Sublime Text 3/Packages
zip path: /C/Users/SWUNQ/AppData/Roaming/Sublime Text 3/Installed Packages
ignored_packages: ["SideBarEnhancements", "SublimeCodeIntel", "Vintage"]
pre session restore time: 0.163017
startup time: 0.217017
first paint time: 0.217017
first paint time: 0.217017
reloading plugin Default.auto_indent_tag
reloading plugin Default.block
reloading plugin Default.comment
reloading plugin Default.convert_syntax
reloading plugin Default.copy_path
reloading plugin Default.delete_word
reloading plugin Default.detect_indentation
reloading plugin Default.duplicate_line
reloading plugin Default.echo
reloading plugin Default.exec
reloading plugin Default.fold
reloading plugin Default.font
reloading plugin Default.goto_line
reloading plugin Default.history_list
reloading plugin Default.indentation
reloading plugin Default.kill_ring
reloading plugin Default.mark
reloading plugin Default.new_templates
reloading plugin Default.open_context_url
reloading plugin Default.open_file_settings
reloading plugin Default.open_in_browser
reloading plugin Default.pane
reloading plugin Default.paragraph
reloading plugin Default.paste_from_history
reloading plugin Default.profile
reloading plugin Default.quick_panel
reloading plugin Default.run_syntax_tests
reloading plugin Default.save_on_focus_lost
reloading plugin Default.scroll
reloading plugin Default.set_unsaved_view_name
reloading plugin Default.show_scope_name
reloading plugin Default.side_bar
reloading plugin Default.sort
reloading plugin Default.swap_line
reloading plugin Default.switch_file
reloading plugin Default.symbol
reloading plugin Default.transform
reloading plugin Default.transpose
reloading plugin Default.trim_trailing_white_space
reloading plugin CSS.css_completions
reloading plugin Diff.diff
reloading plugin HTML.encode_html_entities
reloading plugin HTML.html_completions
reloading plugin 0_package_control_loader.00-package_control
reloading plugin 0_package_control_loader.02-bz2
reloading plugin Clang Format.clang_format
reloading plugin Markdown HTML Preview.MarkdownHtmlPreview
reloading plugin Package Control.1_reloader
reloading plugin Package Control.2_bootstrap
reloading plugin Package Control.Package Control
reloading plugin Sublimerge Pro.Sublimerge
reloading plugin ConvertToUTF8.ConvertToUTF8
reloading plugin Highlight.SublimeHighlight
reloading plugin LaTeXTools.00_add_external_libs_to_path
reloading plugin LaTeXTools.01_reload_submodules
reloading plugin LaTeXTools.02_temp_file_cleanup
reloading plugin LaTeXTools.biblatex_crossref_completions
reloading plugin LaTeXTools.biblatex_field_name_completions
reloading plugin LaTeXTools.biblatex_name_completions
reloading plugin LaTeXTools.biblatex_snippet_completions
reloading plugin LaTeXTools.biblatex_syntax_listener
reloading plugin LaTeXTools.change_environment
reloading plugin LaTeXTools.create_mousemap
reloading plugin LaTeXTools.delete_temp_files
reloading plugin LaTeXTools.detect_spellcheck
reloading plugin LaTeXTools.getRegion
reloading plugin LaTeXTools.getTeXRoot
reloading plugin LaTeXTools.jumpto_anywhere
reloading plugin LaTeXTools.jumpto_tex_file
reloading plugin LaTeXTools.jumpToPDF
reloading plugin LaTeXTools.kpsewhich
reloading plugin LaTeXTools.latex_cite_completions
reloading plugin LaTeXTools.latex_cwl_completions
reloading plugin LaTeXTools.latex_env_completions
reloading plugin LaTeXTools.latex_fill_all
reloading plugin LaTeXTools.latex_input_completions
reloading plugin LaTeXTools.latex_installed_packages
reloading plugin LaTeXTools.latex_own_command_completions
reloading plugin LaTeXTools.latex_ref_completions
reloading plugin LaTeXTools.latexCommand
reloading plugin LaTeXTools.latexDocumentationViewer
reloading plugin LaTeXTools.latexEnvCloser
reloading plugin LaTeXTools.latexEnvironment
reloading plugin LaTeXTools.latextools_default_settings
reloading plugin LaTeXTools.latextools_plugin
reloading plugin LaTeXTools.makePDF
reloading plugin LaTeXTools.migrate
reloading plugin LaTeXTools.parseTeXlog
reloading plugin LaTeXTools.texcount
reloading plugin LaTeXTools.texMacro
reloading plugin LaTeXTools.texSections
reloading plugin LaTeXTools.texSyntaxListener
reloading plugin LaTeXTools.toggle_auto
reloading plugin LaTeXTools.toggle_focus
reloading plugin LaTeXTools.toggle_fwdsync
reloading plugin LaTeXTools.toggle_show
reloading plugin LaTeXTools.toggle_view_on_build
reloading plugin User.compile_with_xelatex
plugins loaded
Loading LaTeXTools plugins...
Loaded LaTeXTools plugins ['traditional_bibliography', 'new_bibliography'] from path C:\Users\SWUNQ\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\bibliography_plugins
Loaded LaTeXTools plugins [] from path C:\Users\SWUNQ\AppData\Roaming\Sublime Text 3\Packages\User
Loaded LaTeXTools plugins ['base_viewer'] from path C:\Users\SWUNQ\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\viewers\base_viewer.py
Loaded LaTeXTools plugins ['command_viewer', 'evince_viewer', 'zathura_viewer', 'preview_viewer', 'sumatra_viewer', 'okular_viewer', 'skim_viewer'] from path C:\Users\SWUNQ\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\viewers
Loaded LaTeXTools plugins [] from path C:\Users\SWUNQ\AppData\Roaming\Sublime Text 3\Packages\User
Loaded LaTeXTools plugins ['pdf_builder'] from path C:\Users\SWUNQ\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\builders\pdfBuilder.py
Loaded LaTeXTools plugins ['script_builder', 'basic_builder', 'traditional_builder', 'simple_builder'] from path C:\Users\SWUNQ\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\builders
Loaded LaTeXTools plugins [] from path C:\Users\SWUNQ\AppData\Roaming\Sublime Text 3\Packages\User
Package Control: Skipping automatic upgrade, last run at 2016-08-19 12:17:50, next run at 2016-08-19 13:17:50 or after
```

**Comment by ig0774** [comment] 2016-08-19 06:31
@swun90: You say that the behaviour occurs with LaTeXTools **either** installed or removed? If it happens when LaTeXTools is removed, then it's to do with your local configuration. I'd check your user keymap (**Preferences | Keybindings — User**) or use the [FindKeyConflicts](https://packagecontrol.io/packages/FindKeyConflicts) plugin (using the `All Key Maps to Buffer` command) to find out what is bound to the `{` press.

**Comment by ig0774** [comment] 2016-08-19 06:59
@swun90: Re: Tab completion: We haven't done anything to disable tab completions, though the non-CWL completions *were* updated to not apply if you're in math mode. That shouldn't change things in a new, blank file.

Standard completion:
![shows \usepackage completion triggered by tab after typing "use"](https://cloud.githubusercontent.com/assets/212893/17801226/ac445d56-65e0-11e6-921a-f98eb752dbe6.gif)

Note that for the standard completion to work, you do need to type `use` and then press tab or explicitly trigger auto-completions (`ctrl+space`) and select the `use` snippet:

![shows the \usepackage completion triggered by launching auto-completions and selecting the "use" snippet](https://cloud.githubusercontent.com/assets/212893/17801470/492ad4a0-65e2-11e6-8f17-3ae425c2850e.gif)

If the standard completions do not work, it's likely that the `tab_completion` setting has been set to `false` either in your `Preferences.sublime-settings` file (**Preferences | Settings – User**) or in your LaTeX syntax settings file (**Preferences | Settings – More | Syntax Specific – User** when run from a view set to the LaTeX syntax).

**Comment by swun90** [comment] 2016-08-19 07:11
Thank you @ig0774 . 
The `tab_completion` seems OK, but I set it to be true in `Preferences.sublime-settings` and it gets right.

As for the key-conflicts, it's a little long. So if convenient, you can see it here [https://github.com/swun90/SwunProgram/blob/master/AllKeyMappings_4ST3LaTeXToolsIssue133.log](url)

**Comment by ig0774** [comment] 2016-08-19 07:20
@swun90: So starting at [line 690](https://github.com/swun90/SwunProgram/blob/master/AllKeyMappings_4ST3LaTeXToolsIssue133.log#L690) of the output, it indicates that your User keymap file defines three rules that apply when typing `{` in a LaTeX file. The first two rules appear to be copies of a previous version of the rules LaTeXTools used. These rules no longer function and need to be removed. I'd probably remove the third rule as well for future safety, since it doesn't seem to do anything other than what LaTeXTools already does (compare 692 to 689).

**Comment by swun90** [comment] 2016-08-19 07:37
@ig0774 Thank you! I delete all the three `{` bindings in `Key Bindings - User` and this issue is solved.
You are really a lifesaver!

**Comment by McCreesh** [comment] 2016-08-28 18:03
I have this same issue, and am able to see the same 3 key conflicts.  However, when I choose Key Bindings - User, I come up with an empty file.  Any recommendations?

**Comment by r-stein** [comment] 2016-08-28 19:18
@McCreesh Have you never set up any keybinding? You could look for a `Default.sublime-keymap` in 
- OS X: ~/Library/Application Support/Sublime Text 3/User
- Windows: %APPDATA%\Sublime Text 3\User
- Linux: ~/.config/sublime-text-3/user

@ig0774 We might also just readd the commands as proxy and just run a call for the new command inside.

**Comment by ig0774** [comment] 2016-08-30 11:43
Two small corrections to @r-stein's comment above:

1. The file (if it exists) is usually named `Default (<OS>).sublime-keymap`, e.g., `Default (Windows).sublime-keymap`. It's possible that there's a file named `Default.sublime-keymap`, in which case, this would explain why the **Key Bindings – User** command doesn't work.
1. The file is actually one folder deeper than suggested:

 * OSX: ~/Library/Application Support/Sublime Text 3/Packages/User
 * Windows: %APPDATA%\Sublime Text 3\Packages\User
 * Linux: ~/.config/sublime-text-3/Packages/User
 
 Obviously, substituting 2 for 3 if you're using ST2. This folder can be easily found by running the **Preferences: Browse Packages** command from the command palette (`C-shift-p`) and selecting the **User** folder.

@McCreesh: If you *still* can't find the file, its possible the bindings are added by a different package (I hope not though!). The second column in the FindKeys output will tell you what package the keymap is from. It would be helpful to see what the output actually is.

**Comment by r-stein** [comment] 2016-09-26 20:15
Since there are no more comments I will close this issue.

**Closed by r-stein** 2016-09-26 20:15 UTC
Labels: reproduction needed
