### ISSUE TITLE
Autocompletion on Sublime 4 doesn't insert backslash

### ISSUE THREAD

**Issue by rotmaus** [SublimeText/LaTeXTools#1517] opened 2021-03-30 09:32 UTC
Then using built-in autocompletion (typing backslash) backslash itself is deleted after inserting the autocompletion text.
![sublime4](https://user-images.githubusercontent.com/3464482/112967378-82ebd380-914b-11eb-9878-9227d4cda462.gif)

**Comment by octiler** [comment] 2021-04-10 18:37
Duplicate of #1506

**Comment by maurice-schleussinger** [comment] 2022-06-03 16:16
This issue is resolved with the ST 4 beta release, see the README on how to install it.

**Comment by deathaxe** [comment] 2024-12-27 18:19
Fixed by v4.

**Closed by deathaxe** 2024-12-27 18:19 UTC
