### ISSUE TITLE
How to configure the files generated after built?

### ISSUE THREAD

**Issue by Voyga** [SublimeText/LaTeXTools#559] opened 2015-09-27 09:50 UTC
Things like `.aux`, `.log`, `.synctex.gz` will be generated after built.
How do I configure the output files if I only want the `.pdf`?

**Comment by ig0774** [comment] 2015-09-27 11:12
You can't really configure LaTeX not to generate `.aux` and `.log` files. `.aux` is essential to LaTeX's operation and `.log` is essential to LaTeXTools understanding what happened (the messages about errors and warnings are generated from reading the log). So configuring a build to not generate those files isn't really an option. You can, however, run the `LaTeXTools: Delete Temporary Files` command available either on the command palette (`ctrl + shift + p` on most systems, `⌘ + shift + p` on Mac) or using the shortcut (`ctrl + l, backspace` or `⌘ + l, delete`), which will clear all those files.

`.synctex.gz` is a bit different because it isn't actually essential to the LaTeX build process. If you are using the traditional builder (and only the traditional builder, since the commands for the simple builder are hard-coded) you can change the `command` option in the `builder_settings` section of your `LaTeXTools.sublime-settings` file. The default is something like this: `"latexmk -cd -e pdflatex = '%E -interaction=nonstopmode -synctex=1 %S %0' -f -pdf"`. Just change that to `"latexmk -cd -e pdflatex = '%E -interaction=nonstopmode %S %0' -f -pdf"`. Note, however, that doing so will break the jump to pdf functionality, and I don't know what the outcome will be (i.e. if it will work at all).

Your best option, however, is just to run the `LaTeXTools: Delete Temporary Files` command after building.

**Comment by Voyga** [comment] 2015-09-27 13:35
Thanks for explaining!

Yes I think run `LaTeXTools: Delete Temporary Files` is my best option.

**Comment by jirkadus** [comment] 2015-10-11 15:16
Any chance to at least set the path for all, but pdf files to be stored in separate folder? Any ideas? Miktex has a -aux-directory=DIR option, is it possible to use it in builder settings within the LaTeX Tools?

**Comment by ig0774** [comment] 2015-12-08 13:42
Support for `-aux-directory` and `-output-directory` has been frequently requested and is somewhere on the TODO list (e.g. #98, #161, #163). Part of the problem is supporting things in a cross-platform way (e.g., TeXLive does not support `-aux-directory`; MiKTeX and TeXLive consequently have different interpretations of what `-output-directory` means) and part of the problem is just ensuring that we understand these implications and implement things in a sane way.

@Voyga: Are you happy to close this issue?

**Comment by ig0774** [comment] 2016-06-18 13:39
I'm closing this for now. Version v3.8.0 adds support for `--output-directory` and a `copy_on_build` option, which should enable you to hide the `aux` files etc.

**Closed by ig0774** 2016-06-18 13:39 UTC
Labels: enhancement
