### ISSUE TITLE
Math preview not working but everything seems fine

### ISSUE THREAD

**Issue by NeoFantom** [SublimeText/LaTeXTools#1405] opened 2019-04-18 13:25 UTC
Math preview isn't working. As this picture shows:

![image](https://user-images.githubusercontent.com/38828722/56363921-df37e000-621f-11e9-9099-0285162177a0.png)

When I run check system, everything is OK:

```
Program      Location                                           Status     Version
-------      --------                                           ------     -------
sublime      D:\Program Files\Sublime Text 3\sublime_text.exe   available  Sublime Text Build 3207
latexmk      D:\texlive\2018\bin\win32\latexmk.exe              available  Latexmk, John Collins, 25 October 2018. Version 4.61
pdflatex     D:\texlive\2018\bin\win32\pdflatex.exe             available  pdfTeX 3.14159265-2.6-1.40.19 (TeX Live 2018/W32TeX)
xelatex      D:\texlive\2018\bin\win32\xelatex.exe              available  XeTeX 3.14159265-2.6-0.99999 (TeX Live 2018/W32TeX)
lualatex     D:\texlive\2018\bin\win32\lualatex.exe             available  This is LuaTeX, Version 1.07.0 (TeX Live 2018/W32TeX)
biber        D:\texlive\2018\bin\win32\biber.exe                available  biber version: 2.12
bibtex       D:\texlive\2018\bin\win32\bibtex.exe               available  BibTeX 0.99d (TeX Live 2018/W32TeX)
bibtex8      D:\texlive\2018\bin\win32\bibtex8.exe              available  This is 8-bit Big BibTeX version 0.99d
kpsewhich    D:\texlive\2018\bin\win32\kpsewhich.exe            available  kpathsea version 6.3.0
magick       D:\Program Files\ImageMagick-7.0.8-Q16\magick.exe  available  ImageMagick 7.0.8-40 Q16 x64 2019-04-13 http://www.imagemagick.org
ghostscript  D:\texlive\2018\tlpkg\tlgs\bin\gswin32c.exe        available  GPL Ghostscript 9.26 (2018-11-20)

Packages for equation preview  Status
-----------------------------  ------
standalone                     available
preview                        available
xcolor                         available
amsmath                        available
amssymb                        available
latexsym                       available
mathtools                      available

Builder  Status
-------  ------
basic    available

Builder Setting  Value
---------------  -----
display_log      False
linux            {}   
osx              {}   
windows          {}   

TeX Root
--------
D:\All\Graduating Paper\Math\HuiqiXue-Math\chapters\chap02.tex

LaTeX Engine
------------
pdflatex    

Viewer   Status     Location
------   ------     --------
sumatra  available  C:\Program Files\SumatraPDF\SumatraPDF.exe
```

When I run show report, it shows only one line:

`Failed to convert pdf to png to preview.`

What is the problem?

**Comment by NeoFantom** [comment] 2019-04-18 15:42
I finally found that there are some curly braces that don't match before this part of text. I suggest everyone who sees this problem to try to compile first, and see if it's because of some type errors (a compilation should make these errors easy to find).

**Comment by r-stein** [comment] 2019-04-18 18:14
The expected behavior is that if the compilation fails the the error message should be "Failed to run pdflatex to create pdf to preview" and the report should contain the latex file and the whole compilation log.
I am not sure why your error occurs. It might be the case that it the compilation created a broken oder empty pdf.

**Comment by NeoFantom** [comment] 2019-04-18 23:54
> The expected behavior is that if the compilation fails the the error message should be "Failed to run pdflatex to create pdf to preview" and the report should contain the latex file and the whole compilation log.
> I am not sure why your error occurs. It might be the case that it the compilation created a broken oder empty pdf.

How can I clean up the temp files created for compilation?

**Comment by ig0774** [comment] 2019-04-19 03:23
They’re deleted automatically. No intervention is required (we only keep the generated PNGs.

Are you using the preview build? I think it has better handling for this situation.

**Comment by NeoFantom** [comment] 2019-04-19 04:04
> They’re deleted automatically. No intervention is required (we only keep the generated PNGs.
> 
> Are you using the preview build? I think it has better handling for this situation.

I'm using sublime 3.2.1, the latex stable version. Are u suggesting me to use the preview version of Sublime Text?

**Comment by ig0774** [comment] 2019-04-22 19:08
No not a preview version of ST, but of the LaTeXTools package. Basically, this issue seems to be a duplicate of #1148. In particular, for TeXLive 2017 on Windows the bundled Ghostscript version doesn't work. The easiest solution is to just install [Ghostscript](https://www.ghostscript.com/download/gsdnld.html) either via the installer there or Chocolatey. However, if you use the preview version of LaTeXTools, which may be unstable, this issue should be fixed there.

**Closed by ig0774** 2019-04-22 19:08 UTC

**Comment by NeoFantom** [comment] 2019-04-23 06:54
> No not a preview version of ST, but of the LaTeXTools package. Basically, this issue seems to be a duplicate of #1148. In particular, for TeXLive 2017 on Windows the bundled Ghostscript version doesn't work. The easiest solution is to just install [Ghostscript](https://www.ghostscript.com/download/gsdnld.html) either via the installer there or Chocolatey. However, if you use the preview version of LaTeXTools, which may be unstable, this issue should be fixed there.

I do have the standalone Ghostscript installed on my PC and the path variable is set. But latexTools `check system` still shows only the builtin version of gs in latex. How to cope with that?

**Comment by ig0774** [comment] 2019-04-23 17:02
You can see the `PATH` variable as LaTeXTools sees it by running the **Check System** command. This, in turn, is controlled by the `"texpath"` setting which, by default, is blank on Windows, but if you've set it to a non-blank, should have `$PATH` or `%PATH%` in it somewhere.
