### ISSUE TITLE
Pauses when typing \ in math mode

### ISSUE THREAD

**Issue by catch22** [SublimeText/LaTeXTools#805] opened 2016-08-09 03:13 UTC
When I type `\{ \foo` in a math environment (in this case, `align*`) then the following undesirable things happen:

1. Upon typing `{`, a popup appears that lets me select a reference.
2. Upon typing the second `\`, there is a long pause after which another unwarranted popup appears.

I'm running the latest LaTeXTools and Sublime 3/64-bit/Linux. Thanks for your help.

**Comment by xmlu** [comment] 2016-08-09 06:49
Similar problem for Sublime 3/64-bit/Mac OS.

An undesirable popup appears when I type \{ in math mode.

**Comment by r-stein** [comment] 2016-08-09 10:36
I tried to reproduce it on windows, but it worked as usual. Can you open the ST console ``ctrl+` ``, write `sublime.log_commands(True)`, and check which commands are executed?

The popup is a real popup not the autocomplete popop?

**Comment by xmlu** [comment] 2016-08-09 12:56
The executed command is `command: latex_fill_all {"completion_type": "ref", "insert_char": "{"}`

**Comment by r-stein** [comment] 2016-08-09 13:56
This should be fixed in release `v3.10.6`

**Comment by r-stein** [comment] 2016-08-09 13:58
Is the popup from `2.` the autocompletion popup with LaTeX commands?

**Comment by xmlu** [comment] 2016-08-09 14:08
The popup is the same as the one invoked by `\ref{`.

**Comment by catch22** [comment] 2016-08-09 17:53
Both popups were autocompletion popups for references, and the popup from `2.` displayed fewer references than the first one.

I've just updated and I think it works fine now - there is much less lag, and the autocompletion popups upon typing `\` are now for LaTeX commands instead of references.

I'll see if there are any remaining problems popping up through today's work - otherwise, thanks very much for fixing! :smile:

**Comment by r-stein** [comment] 2016-08-09 18:27
The small lag happens, because it also completes your command definitions (`\newcommand{\mycommand}{...}`) https://github.com/SublimeText/LaTeXTools/pull/711. Since the result is cached, it should only occur once in 30 mins. It would be possible to move that into a separate thread and improve the analysis performace.

I will close the issue. Feel free to reopen it, if the problem persists.

**Comment by catch22** [comment] 2016-08-09 18:28
Wonderful, thank you.

**Closed by r-stein** 2016-08-09 18:27 UTC
Labels: bug

**Comment by ig0774** [comment] 2016-08-09 23:17
It's probably worth mentioning that the new cwl code (from #623) by itself is a bit slower than the previous code on the initial run. This is because the first time its run, it parses *all* the cwl files.
