### ISSUE TITLE
bugs in cite command with multiple sources and compilation log results with using of special output directory for temporary files 

### ISSUE THREAD

**Issue by mrshu2** [SublimeText/LaTeXTools#813] opened 2016-08-12 06:22 UTC
Using ST3 build 3114.
1. "builder": "basic"; "output_directory": "./tmp"; "hide_build_panel": "no_errors"; other settings are defaults
Even there are actual errors in pdflatex compilation of source file builder results panel never shows them.
2. "bibliography": "traditional"; other settings are defaults
When using underscore symbol in bib labels (ex. "bib:Author_2016") autocomplete multiple bib sources using comma after the first successful insertion from correctly generated labels list leads to unpredictable behaviour (incorrect content of labels list and corruption of all inserted labels to cite command).

**Comment by r-stein** [comment] 2016-08-12 08:45
1. Are the errors listed in the output panel, if you change the `hide_build_panel` option to `"always"`? If not it might be useful, if you could provide further information like the output log file.
2. Thanks for the report, it will be fixed soon.

**Comment by ig0774** [comment] 2016-08-12 09:20
@r-stein:  re: 1 You mean `"never"` right? `"always"` will always hide the build panel.

**Comment by mrshu2** [comment] 2016-08-12 11:24
I'm working with the project that consists of multiple tex files: the main one (book.tex) with multiple includes through \input directive. Only one of the included files contains error (ch03.tex). If I leave only one input directive with this problem file (\input{ch03}) and comment all the others LaTeXTools builder correctly detects the error(corresponding logs are attached: correct_err_detect.log and build_panel_correct_err_detect.log). When I uncomment one other file (ch05.tex) builder don't detect any errors, only some warnings (no_err_detect.log and builder_panel_no_err_detect.log).
 
[pdflatex_LTbuilder_logs.zip](https://github.com/SublimeText/LaTeXTools/files/415160/pdflatex_LTbuilder_logs.zip)

**Comment by ig0774** [comment] 2016-08-12 12:25
@mrshu2: So the underlying issue appears to be with parsing your logs. In both cases, you get the `"(Log parsing issues. Disregard unless something else is wrong.)"`  message, which indicates some sort of issue.

In the case of the one where it is working, it appears to be that its not properly determining where certain files are being closed which mean some of those warnings and errors might be reported against incorrect locations. In the case where it is not working, I'm not exactly sure why, but for some reason its exiting before it gets to the error message, hence LaTeXTools thinks there aren't any errors and the panel gets hidden. We'll try to get the parsing issues tracked down and resolved, but that isn't always easy to do.

**Comment by ig0774** [comment] 2016-08-14 09:58
Ok... I kind of suspected this was related to Cyrillic characters in your path and it is, but not in the way I expected.

Basically, whenever your log file indicates that it's opening a file in the output directory, it logs it as using the path:

`/home/roman/rudshtein_r/Документы/ЭЛУ/Книга Ризахано??а/rnebook/tmp/`

Instead of the correct path:

`home/roman/rudshtein_r/Документы/ЭЛУ/Книга Ризаханова/rnebook/tmp/`

Why that single character gets messed up, I'm not sure, but the message is from `pdfTeX` itself. 

The problem is that in order to tell whether or not a logged file is valid, LaTeXTools calls `os.path.isfile()` which checks to see if the file exists. Obviously, any file with an invalid path will be reported as not existing and `/home/roman/rudshtein_r/Документы/ЭЛУ/Книга Ризахано??а/rnebook/tmp/` is not a valid path on your system. 

This means that every time `pdfTeX` tries to open a file written to the output directory (`book.aux`, `book.toc`, `book.bbl`, etc.), LaTeXTools thinks it's not a valid file and so it doesn't get added to the stack we use to track the currently opened file.

Since the file wasn't added to the stack, when it is closed (i.e., when there's a `)` encountered in the log), LaTeXTools pops the wrong file off the stack. Eventually, because more files are popped from the stack than are added to it, the file-tracking stack will be empty when a file appears to close, at which point LaTeXTools bails on the log file. This is why adding or removing a file changes whether the error message gets displayed: it changes the point where the stack runs out. If the stack runs out before the error message is encountered, it never gets reported back.

There are several things I can think of that would address this, but none of these are ideal solutions:

1. If a file doesn't appear to be a file, we could try to match the extension against a short list of known file extensions that appear in the output directory (such as `aux`, `bbl`, `out`, `.nlo`, etc.). If that matches the file extension, then we just assume the file exists. As long as the list of extensions is (relatively) short, this would be unlikely to yield false positives. However, such a list would (invariably) be incomplete so this issue would likely resurface again.

1. The reason that the absolute path appears in the log *at all* is because we pass the absolute path to `--output-directory` or `--aux-directory`, even if the path is specified as a relative path. The reason for doing this, in turn, is because MiKTeX will fail if `--output-directory` or `--aux-directory` contains a `../` (it's a security concern...). Now because you're using `./tmp` (i.e. a relative path with only ASCII characters and on TeXLive to boot) if we were to pass the relative path instead of the absolute path it would work in this instance. There are three draw backs: 1) we'd have to implement somewhat different code for MiKTeX and TeXLive, 2) we'd have to add more checks to see if the output directory was a relative path in the various places it's used, and 3) it perfectly possible to specify a relative path with non-ASCII character which may cause the same malfunction.

1. (The simplest) we remove the bail condition from the parse_tex_log routine. This means you will always get all errors, warnings, etc. (something the current implementation doesn't guarantee). The downside is that the file information for those errors, warnings, etc. will be substantially less trust-worthy or even missing altogether.

**Comment by mrshu2** [comment] 2016-08-15 12:45
@ig0774: Thank you for the detailed description of the problem origin. Switching to ASCII-way naming convention file path I've eliminated the error. 
As for the solutions you proposed, in my opinion the best way is the second one that means to specify a relative aux-directory path for pdflatex compiler.

**Comment by ig0774** [comment] 2016-08-16 15:46
v3.10.8 addresses the issue with underscores in bib labels. I'm still thinking through the implications of the solutions to the other issue.

**Comment by ig0774** [comment] 2016-09-20 11:10
v3.11.0 actually implements the second solution. Thanks for the issue report!

**Closed by ig0774** 2016-09-20 11:10 UTC
Labels: log parsing
