### ISSUE TITLE
latex_fill_all eats following text

### ISSUE THREAD

**Issue by gczzdc** [SublimeText/LaTeXTools#827] opened 2016-09-01 09:06 UTC
If I ref, cite, usepackage, etc., and there is ordinary text immediately following, then after choosing the reference, citation, package, etc., the ordinary text is deleted.

For example, given text

\usepackagefoo

typing { between \usepackage and foo opens a dialog to choose a package. When I choose a package, e.g. 10_5, the output is 

\usepackage{10_5}

rather than the expected

\usepackage{10_5}foo

The typical use case is text 

(\cite) 

which after selection outputs 

(\cite{citation} 

instead of 

(\cite{citation})

**Comment by ig0774** [comment] 2016-09-01 12:10
So the general case, i.e., `\cite{foo`, this is the expected behaviour. Text immediately following the command with no separator is interpreted as a prefix and used to filter the displayed results. The specific case you mention with parentheses, however, is a bug.

**Comment by interrogator** [comment] 2016-09-06 11:04
Just adding a couple of things. First is that a similar thing seems to happen when there is a period/full stop following the citation. This should not be removed, since it has no filtering value, and since it's the most common place for a citation, often inserted later in the writing process. The criteria should likely be something like `[A-Za-z0-9_-]?\s` for activating the filter mode.

Also, I don't seem to get any filtering behaviour anyway. Are we sure it's working?

As a comment, I think it's counter-intuitive that we'd type out part of the entry we want, then type the `\cite` command, and then further specify the thing we want. Why not just use the command, and then get the result from the list. If the problem is speed, it looks like the code that builds the database (i.e. `traditionalBibliography.py` could instead be optimised?

**Comment by ig0774** [comment] 2016-09-09 11:49
The real use-case for it is for a situation where someone has disabled the auto-completions on `{`, but wants to use one of the keybindings to fill in the entry, in which case you might type `\cite{ap` and then hit the key binding to complete things. Nevertheless, you're right. I'll see if I can't get things to behave a bit more intuitively in the case you're talking about.

**Comment by ig0774** [comment] 2016-09-20 11:09
Thanks for the issue report. This is fixed in v3.11.0 which, I think, behaves in a more intuitive way.

**Closed by ig0774** 2016-09-20 11:09 UTC
Labels: bug
