### ISSUE TITLE
Sumatra not launched after successful build

### ISSUE THREAD

**Issue by Gormador** [SublimeText/LaTeXTools#547] opened 2015-08-20 14:27 UTC
Hi,

First of all, thank you for your work!

As for this issue, as per title. Details!:
 - Platform is Windows 8.1.
 - I am able to launch Sumatra from the command line as its folder (not the `.exe` directly; tried both actually) is added to my `Path`.
 - Sumatra is the default pdf viewer -- not that it matters, I guess.
 - I'm using MiKTeX.
 - I've followed your windows specific [instructions](https://github.com/SublimeText/LaTeXTools/blob/master/README.markdown#requirements-and-setup).
 - No error is outputted, the console output of the build is:
```
[Compiling C:\Path\To\My\file.tex]

TraditionalBuilder: Engine: pdflatex -> pdftex. Invoking texify... done.

No errors.

[Done!]
```
 - The full log is boring, too. It ends with:
```
Output written on MyFile.pdf (1 page, 27153 bytes).
SyncTeX written on MyFile.synctex.gz.
Transcript written on MyFile.log.

No errors.

[Done!]
```

In the end, it's strange enough that I'm pretty sure I'm the one who made a mistake or an incorrect assumption somewhere, but really can't tell what.

Anyway, thanks in advance for you answer and, hopefully, a fix :-)

**Comment by ig0774** [comment] 2015-09-02 16:24
Can you run: `import os; print(os.environ['PATH'])` from the SublimeText console? That checks the PATH as SublimeText actually sees it. Also, what happens on the SublimeText console (select **View -> Show Console** after compiling).

One thing to try: in your LaTeXTools preferences file, find the `windows` section of the Platform settings and try setting the `sumatra` setting the full path to SumatraPDF, e.g. `c:\Program Files (x86)\SumatraPDF\SumatraPDF.exe`, and see what happens.

**Comment by msiniscalchi** [comment] 2015-12-10 04:21
Is this resolved? If so please close.

**Comment by msiniscalchi** [comment] 2015-12-15 05:12
Closing as no further comments, but feel free to reopen if the issue is still present and you have new inf for us.

**Closed by msiniscalchi** 2015-12-15 05:12 UTC
