### ISSUE TITLE
No option to leave focus unchanged

### ISSUE THREAD

**Issue by ajnisbet** [SublimeText/LaTeXTools#823] opened 2016-08-29 01:34 UTC
After pull https://github.com/SublimeText/LaTeXTools/pull/610, running a build will always cause a focus change, even with `"forward_sync": false`.  With `"keep_focus": false` the pdf viewer is focused, as before. But now setting `"keep_focus": true`  focuses Sublime after the delay amount, instead of leaving the focus unchanged.

This is frustrating if you navigate away from Sublime after building but before the delay, only to be brought back again. 

I  believe that changing
```python
if forward_sync:
    viewer.forward_sync(pdffile, srcfile, line, col, keep_focus=keep_focus)		
if keep_focus:
    focus_st()
```
to
```python
if forward_sync:
    viewer.forward_sync(pdffile, srcfile, line, col, keep_focus=keep_focus)		
    if keep_focus:
        focus_st()
```
 in [jumpToPDF.py](https://github.com/SublimeText/LaTeXTools/blob/8ca20a0f9e07611b3268a41640f956c36237e97f/jumpToPDF.py#L210) would fix this without regressing on  https://github.com/SublimeText/LaTeXTools/issues/495. Is there any reason to focus Sublime when `forward_sync` is `False`? I would be happy to make a PR.

<hr>

For now, setting `"sublime_executable"` to a noop like `":"` prevents the focusing.

**Comment by r-stein** [comment] 2016-08-29 06:57
I agree, that this is an unpleasant behavior and the idea of `keep_focus` was keeping the focus after showing the pdf and *not* indicating a finished build. Hence I will change it for the next release.

> For now, setting `"sublime_executable"` to a noop like `":"` prevents the focusing.

Who don't you just set `keep_focus` to `false`?
https://github.com/SublimeText/LaTeXTools#toggling-window-focus-following-a-build

**Comment by r-stein** [comment] 2016-08-29 07:21
Actually this is the correct behavior and you should set `open_pdf_on_build` to `false` to avoid it. If `open_pdf_on_build` is `true` it will open the pdf in the viewer and if `forward_sync` is also `true` it will additionally scroll to the correct position.

If you did not know: You can quick toggle these settings via `C-l, t, ?`

**Comment by ajnisbet** [comment] 2016-08-29 18:15
> Who don't you just set `keep_focus` to `false`?

That focuses the pdf viewer; the behaviour I'm looking for is nothing gets focused. This is how it was before https://github.com/SublimeText/LaTeXTools/pull/610, and how other build packages work.

>  you should set `open_pdf_on_build` to `false`

Yeah, that should fix it.

FWIW my workflow is to have the pdf viewer open on the first built (with no focus change), then subsequent builds to have no effect on focus. I don't like anything changing what I'm focused on, especially when using multiple workspaces.

But maybe that's not something worth supporting. I'm happy with my hack, and it's documented here for others. Sounds like you're aware of the behaviour, if you're ok with it feel free to close this.

**Comment by r-stein** [comment] 2016-08-29 19:55
Then I would recommend to open the pdf via keybinding `C-l, v` or `C-l, j` and set `open_pdf_on_build` to `false`. We cannot (easily) support something like "open pdf unless it is already open", because it can be complex to detect if it is opened already and it wouldn't be a real advantage anyway.

**Comment by ig0774** [comment] 2016-08-30 11:20
I've re-opened this because I think there is something here that may be worth addressing. In particular, I don't think the problem in question is #610—which does exactly what it was supposed to—but was actually brought about by 93daf30, which was an attempt to fix #689. The change in 93daf30 changed things so that the Evince viewer will proactively ensure Evince gains the focus when `keep_focus` is `false`. This is a change from the behaviour @ajnisbet describes as desirable. Essentially, there's likely something we can do to minimise the number of focus-shifts that occur. They can't be completely eliminated, because, at some point, we have to launch the viewer and when that happens, it will steal the focus, but we may be able to do something a little less proactive when `keep_focus` is `false` by instead noting if we were launched from a keypress or automatically.

Incidentally, @ajnisbet, you haven't made it clear which OS and viewer you are talking about. I've kind of assumed from your remarks its Evince on Linux, which I think is probably addressable. With other viewers, however, such as Okular and SumatraPDF, we are very unlikely to be able to do much useful because all our interactions with them necessarily involve a shift in focus. If I've guessed correctly, this is actually a duplicate of #668, but a helpful discussion for thinking through what might be done.

**Comment by ajnisbet** [comment] 2016-08-30 16:05
Ah yeah, I'm using Evince + Linux. Currently Fedora 34, Gnome 3.20, Sublime 3114 and LatexTools 3.10.11, but it's been happening for a few previous versions of all of the above. 

My understanding is that https://github.com/SublimeText/LaTeXTools/commit/93daf308a4c64d11fd86ff31a399c9d9b9564723 and https://github.com/SublimeText/LaTeXTools/pull/610 were only required to fix focus issues with forward sync (which will always be messy with Evince), but ended up affecting behaviour  under `"forward_sync": false`.

When `keep_focus` is `true` and `forward_sync` is `false`, what interaction is required with any viewer on build? Disabling the focus call under those conditions would fix this issue, and would allow `"forward_sync": false` to fix https://github.com/SublimeText/LaTeXTools/issues/668 as per @r-stein's suggestion.

**Comment by ig0774** [comment] 2016-08-30 17:44
Well, displaying the viewer *at all* is a requirement and *this* is what the `focus_st` thing is about. In any case, I really don't want to touch the logic in the jumpToPDF file at all. For the most part it does what we intend it to (remembering that the same code is run if you're using Evince, Zathura, Okular or Sumatra, all of which have slight differences in how "best" to interact with them). On the other hand, I'm think that by modifying the Evince viewer itself, we might be able to run the focus hack only when we actually need to start Evince (which the viewer is already aware of).

**Comment by ig0774** [comment] 2016-09-13 19:47
Ok, having played around with this a bit, what I was hoping for isn't going to work. The underlying problem is that even just running the `SyncView` function will cause Evince to steal focus. In order to be able to guarantee that the focus remains in ST, we have to run the focus stealing hack. 

Setting `open_pdf_on_build` to `false` will stop Evince (or any viewer) from being launched on build. For future reference, the `keep_focus_delay` can also be reduced, depending on the speed of your computer, which will result in less of a delay between Evince being launched and ST trying to regain focus.

Also, it turns out I misspoke about Okular, which properly supports being launched without trying to steal the focus at all.

Finally, one last point: on build, at least, we really do a forward-sync rather than just launch the viewer. The rationale is so that the position in the viewer is updated to reflect where you are in the editor, which can be useful when working on longer documents, etc.

**Closed by ig0774** 2016-09-13 19:47 UTC
Labels: enhancement

**Comment by caspre24** [comment] 2016-09-22 11:51
Sorry for digging this up again, but I liked the way of bringing the viewer to front on build and then refocus ST.
Currently, when evince is already opened but in the back, a build doesn't do anything. Is there a way back to the old behaviour?
In my understanding, setting all `keep_focus`, `forward_sync` and `open_pdf_on_build` to true should do trick, but doesn't.
Im using Evince on Linux with LaTeXTools v3.11.0 and ST build 3124

**Comment by ig0774** [comment] 2016-09-22 12:41
Interesting to know someone actually likes that behaviour (this request was asking for almost exactly the opposite). At any rate, if this changed in v3.11.0, it would've been fc7aaba that changed things. I'll have to play around with things a bit to see what can be done. Incidentally, what version of Evince are you using?

**Comment by caspre24** [comment] 2016-09-22 12:50
I noticed the opposing biases, made me chuckle ;-)
My Evince is v3.18.2.

**Comment by ig0774** [comment] 2016-11-01 14:45
@caspre24: In v3.12, there is a new option `bring_evince_forward` that goes in the `viewer_settings` block of your settings file. If it is set to `true`, it should get the behaviour you want, i.e., Evince is brought forward and then focus is shifted back to ST.

Regarding the initial issue this was opened to address, in v3.12, I've switched things so that with Evince and Zathura, we shift focus as few times as possible if `keep_focus` is set to true. You can play with the delay between Evince being launched and focus being changed by modifying the `keep_focus_delay` settings in the platform-specific block (i.e. `linux`). If you really hate the focus switching hack, there is a new setting called `disable_focus_hack` which, if set to `true`, will disable LaTeXTools switching the focus altogether. Note, however, this is not the same as saying focus will never change as a result of LaTeXTools actions, since launching Evince tends to steal the focus.
