### ISSUE TITLE
Sublime Text 2 \cite{ and \ref{ menu toggle not working

### ISSUE THREAD

**Issue by ojturner** [SublimeText/LaTeXTools#970] opened 2016-12-02 12:29 UTC
Hello, 

Since a few days ago the \cite{ and \ref{ commands do not bring up the drop down menu within Sublime Text 2 so that I can easily insert these. I didn't make any changes to my settings, one day they worked and the next they do not. 

I was hoping for some advice on what could be the problem? 
Thanks, 
Owen

**Comment by ig0774** [comment] 2016-12-03 08:42
Does it work if you close and re-open ST? There is an issue I discovered when doing some other work that's caused by ST's reloading mechanism. That issue is actually resolved by #955, which should be included in the next release.

**Comment by ojturner** [comment] 2016-12-03 08:45
Yes thanks, I discovered yesterday that it worked after I quit the application and restarted. 
Thanks for your response, issue now seems fixed. 

Owen

**Comment by ig0774** [comment] 2016-12-03 16:16
This should be fixed in v3.12.9. Thanks for the issue report.

**Closed by ig0774** 2016-12-03 16:16 UTC
Labels: bug
