### ISSUE TITLE
Problem parsing log file

### ISSUE THREAD

**Issue by semorrison** [SublimeText/LaTeXTools#539] opened 2015-08-04 01:36 UTC
I'm getting an error while compiling, saying that there was a problem parsing the log file. 

The log file looks innocuous to me (it's available at http://pastebin.com/CzKTU4my). The only thing that I do that is a bit strange is use a class file that internally uses \LoadClass{beamer}. If I just use \documentclass{beamer} directly LaTeXTools successfully parses the log file.

**Comment by ig0774** [comment] 2016-02-16 13:26
Basically what breaks here is the bit where the log parsing code tries to keep track of which file is currently being executed. 

The problem is that your class with the `\LoadClass{beamer}` command generates this line in your example log:

```
(../lecture.cls (/usr/local/texlive/2015/texmf-dist/tex/latex/beamer/beamer.cls
```

Which indicates opening *two files*. The log parser currently assumes that there is only one file per line, as in the next line in your sample log, which is more typical:

```
(/usr/local/texlive/2015/texmf-dist/tex/latex/beamer/beamerbasercs.sty
```

You get an error, then, because (to the log parser) it is getting one more closing parenthesis then it expected (i.e., when LaTeX is through processing `beamer.cls` the parser will think it is done processing `lecture.cls` when `lecture.cls` actually finishes, it won't think there are any more files to be processed). This probably doesn't happen when you directly use `\documentclass{beamer}`.

So that's why you're getting a parsing error...

**Comment by ig0774** [comment] 2016-07-03 21:45
Thanks for the log file and issue report. That log file should be properly parsed by the current version, and hopefully any other similar logs.

**Closed by ig0774** 2016-07-03 21:45 UTC
Labels: log parsing
