### ISSUE TITLE
How to compile auxiliary files to a different folder on TexLive/Mac?

### ISSUE THREAD

**Issue by nunoh** [SublimeText/LaTeXTools#383] opened 2014-04-23 16:52 UTC
With so many updates to the build files in LatexTools and LaTeX compilers themselves, I admit I am confused about what and where I should change in order to be able to have something like automatically place all the temporary build files such as the ``.aux, .log, .bbl``, etc.. in something like a ``tmp`` folder.

Naturally, browsing the internet I came across some solutions that have worked for others, but not for me (yet) though. They are the optional flags of: ``-aux-directory=/some/temp/dir <additional options>`` in this SO thread (http://stackoverflow.com/questions/3745908/i-dont-want-the-aux-log-and-synctex-gz-files-when-using-pdflatex).

Has anyone been able to achieve something like that and would care to share or simply knows how to do it and/or can guide me doing that? That would be great!

I am using TexLive 2013 and on a Mac. 

Many thanks.

**Comment by ig0774** [comment] 2015-09-27 11:04
Unfortunately, this isn't really possible without changes to TeXLive. the `-aux-directory` flag is only implemented in the MiKTeX version of `pdflatex` and friends, so its limited to MiKTeX and hence to Windows. There is an `-output-directory` option, but that will move the final output, e.g., `.pdf` or `.dvi` file as well, which may be what you want to achieve... 

Obviously, it's possible to right a script to move the temporary build files, but then you may as well have deleted them, as they won't be picked up on the next build. (Which you can do, incidentally, but pressing `⌘+L, delete`).

Although it's possible to change the command used by the traditional builder to set either the `-aux-directory` or `-output-directory` option, I'd note that using either of those will cause LaTeXTools not to function properly (using `-aux-directory` it will not find the log file; using `-output-directory` it will not find the pdf either).

Perhaps it would meet your needs if a flag was added to enable the deletion of the generated files after build? That could be implemented fairly simply.

**Comment by msiniscalchi** [comment] 2015-12-10 04:14
Duplicate of #161 (and something that **eventually** we'll tackle once and for all, but not now). Closing.

**Closed by msiniscalchi** 2015-12-10 04:14 UTC
