### ISSUE TITLE
Build doesn't work with ISO 8859-1

### ISSUE THREAD

**Issue by pedromss** [SublimeText/LaTeXTools#635] opened 2016-01-03 22:15 UTC
I'm using **ST3** on windows 10, and have this repository added to package control (so I'm assuming I have the latest version of LaTeXTools installed).

The `Ctrl + B` build shortcut works perfectly along with the TEXRoot `%!TEX root = <file-name>.tex` directive when the file is saved in UTF-8. Unfortunately for me this encoding doesn't support some accented characters in my native language. So when I save the file with ISO 8859-1 the build shortcut stops working at all, not even the single file is compiled. 

Since I can invoke the build command with both encodings in a java file, I'm assuming the problem lies with LaTeXTools.

If someone knows how to fix this or can confirm if the problem is with LaTeXTools, I would appreciate.

**Comment by msiniscalchi** [comment] 2016-01-03 22:49
LaTeXTools does its best to support UTF-8, but other encodings are really not supported at the moment. Now, there are two kinds of issues:

1. file/path issues: this is when your file names, or directory names, contain non-ASCII or non-UTF-8 characters. 
2. source file issues: if the non-UTF-8 characters are in the file itself.

Now, the fact that things work if the file is saved with UTF-8 encoding suggests that the problem is n.2; however, the fact that the build command does nothing suggests that it's n.1.  To clear things up, what do you see in the ST console (ctrl-backtick)?

**Comment by pedromss** [comment] 2016-01-03 23:04
When I run the build command on a file saved with encoding UTF-8 the output says `Finished normally` (although it doesn't generate the pdf, due to errors of missing `$` which are there due to the accented characters.

This is the output in ST console when I run the  build command on a file saved with ISO 8859-1 encoding.
Welcome to thread Thread-20
`['texify', '-b', '-p', '--engine=pdftex', '--tex-option="--synctex=1"', '<file-name>.tex']`
Finished normally
0
False True True
`!TEX root =  '<path>'`
Jump to:  9 8
Windows, Calling Sumatra
Traceback (most recent call last):
  File `"<path-to>st3\sublime_plugin.py"`, line 533, in run_
    return self.run(**args)
  File `"<path-to>AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\makePDF.py"`, line 296, in run
    self.file_name = getTeXRoot.get_tex_root(view)
  File `"<path-to>\AppData\Roaming\Sublime Text 3\Packages\LaTeXTools\getTeXRoot.py"`, line 54, in get_tex_root
    for line in lines:
  File "./codecs.py", line 693, in __next__
  File "./codecs.py", line 624, in __next__
  File "./codecs.py", line 537, in readline
  File "./codecs.py", line 483, in read
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe9 in position 0: invalid continuation byte

**Comment by msiniscalchi** [comment] 2016-01-03 23:13
OK, so does the *file name* contain any non-ASCII characters? what happens if you rename the file so it only uses ASCII?

**Comment by pedromss** [comment] 2016-01-03 23:25
The current file name is `ex3.tex` and the root file is `LI51N_G7_SE3.tex` I believe these are all ascii characters?

**Comment by msiniscalchi** [comment] 2016-01-03 23:58
Indeed they are. I see what's going on; the multi-file code opens your file in UTF-8 mode, with strict error enforcing. There may be a simple way to fix this, but as a workaround, define a project file and specify the TEX root file there (see the README for details on how to do so). This should short-circuit the code that looks for the %!TEX root = line in your file.

**Comment by pedromss** [comment] 2016-01-04 09:34
I created a `.sublime-project` file in the same directory as the `.tex` files, with the following content:
`{
    "settings": {
        "TEXroot": "LI51N_G7_SE3.tex",
        "tex_file_exts": [".tex"]
    }
}`

Should it build with that? 

Also I noticed something else, 2 other files in the same folder, saved with the ISO 8859-1 encoding and with the `#! TEX root = <file-name>.tex` directive trigger the build command. This weird because now I have no idea what it might be...

**Comment by ig0774** [comment] 2016-01-04 10:02
The `"TEXroot"` setting in a project file should be an absolute path (see, e.g. #630 and #152). Strictly speaking, you don't *need* the `"tex_file_exts"` setting, but it doesn't do any harm.

As for what's probably happening with the other files, I'm guessing that in the failing file you have a comment *before* the `%!TEX root` directive that has an accented character? It looks like it's choking on an "é"...

**Comment by pedromss** [comment] 2016-01-04 10:38
Now with:
`{
    "settings": {
        "TEXroot": "G:/repos/si-1516-LI51N-G7/relatorio_se3/LI51N_G7_SE3.tex",
        "tex_file_exts": [".tex"]
    }
}`

The problem persists. In the failing file the tex root directive is the first thing in the file, line 1, with nothing else on this line.

However the full path hint drove me to try placing the absolute path in the tex root directive which worked! However since this is a shared project I can't have absolute path in the source files. 

The project file seems like the correct choice but its not working. I created it as a dot file, does it need to have any specific name? Can it be placed in the same directory as the source files?

**Comment by ig0774** [comment] 2016-01-04 11:00
You do need to open the project file in Sublime Text using **Project | Open Project**. [Project files are a Sublime feature](http://www.sublimetext.com/docs/3/projects.html). LaTeXTools doesn't read them directly. The name of the file doesn't matter and it can be placed in the same directory as the source files.

**Comment by pedromss** [comment] 2016-01-04 11:08
Works perfectly. This will serve my needs. Thank you.

**Comment by msiniscalchi** [comment] 2016-01-04 13:35
@ig0774 I'd still like to do something to avoid this kind of failures. In `get_tex_root`, we should add the `ignore` flag to the `codecs.open` call. I'll do this later, hopefully.

**Comment by ig0774** [comment] 2016-01-04 14:45
@msiniscalchi I've just committed that change to master.

**Closed by ig0774** 2016-01-04 14:45 UTC

**Comment by msiniscalchi** [comment] 2016-01-04 15:04
Thanks @ig0774 !
