### ISSUE TITLE
Forward search not working in Skim 1.4.22

### ISSUE THREAD

**Issue by blfang** [SublimeText/LaTeXTools#876] opened 2016-10-19 17:43 UTC
The forward search functionality (both the automatic kind after compiling as well as the manual kind triggered by `C-l,j`) stopped working for me after I updated to Skim 1.4.22. I re-installed an old version (Skim 1.4.21) and the functionality returned.

If it matters, I am on OSX El Capitan 10.11.6 and ST2 Build 3126.

**Comment by xiaoweiz** [comment] 2016-10-20 06:52
I can replicate the issue and the workaround. Btw, the reverse search is working, though.

**Comment by ig0774** [comment] 2016-10-20 11:15
This is a known issue in Skim.app itself (see Skim bug [#1128](https://sourceforge.net/p/skim-app/bugs/1128/)). LaTeXTools ends up calling the embedded `displayfile` script, which no longer works. Unfortunately, the issue is that 1.4.22 introduced a bug in the AppleScript interface, so until a new version is released, there isn't much that can be done.

The best fix is, as has been pointed out, is to revert to 1.4.21, until a new version of Skim is released (a fix has been committed, but no new release has been made).

Alternatively, in a very limited case, i.e., where your document consists of a single LaTeX file and the PDF file and synctex file are output to the same directory as the LaTeX file, you can [download](https://sourceforge.net/p/skim-app/bugs/_discuss/thread/8b194f97/effb/attachment/displayline) a version of the `displayline` script that works with 1.4.22. To use this, do a secondary click on the Skim.app file, select **Show Package Contents** browse to `Contents/SharedSupport` and replace the `displayfile` script with the new one, then from the terminal, run `chmod +x /Applications/Skim.app/Contents/SharedSupport/displayfile` (assuming that Skim.app is installed in `/Applications`). Once again, this "new" `displayfile` script **only** works in the limited circumstance described above, so I really recommend reverting to 1.4.21.

**Comment by ig0774** [comment] 2016-10-31 00:07
I'm closing this issue since it's an issue with Skim that'll hopefully be addressed in their next release.

**Closed by ig0774** 2016-10-31 00:07 UTC
Labels: invalid

**Comment by ig0774** [comment] 2016-11-14 15:48
Skim v1.4.23 has been released and appears to resolve the issue.
