### ISSUE TITLE
Building does not work

### ISSUE THREAD

**Issue by tomaskrehlik** [SublimeText/LaTeXTools#659] opened 2016-03-02 17:58 UTC
After the recent update (today), the building does not work with error in console 

`Unable to find target command: make_pdf`

On Sublime Text 3, Build 3103.

**Comment by msiniscalchi** [comment] 2016-03-02 18:08
There has been no update today... have you tried relaunching ST?

**Comment by manon-henrioux-cko** [comment] 2016-03-02 18:40
Exactly same issue here, Latextools has been updated (see changelog below) and it does not build anymore

>>> Package Control Messages
========================

LaTeXTools
----------

  LaTeXTools Plugin version 3.6.3 (2016-02-25) changelog:
  
  
  New features:
  
  - Set spellchecking language via TEX directives (R. Stein)
  - Input completion for \includesvg
  - Project-relative TEXroot setting
  - Some internal improvements
  
  Bugfixes:
  
  - Internal bugfixes

**Comment by tomaskrehlik** [comment] 2016-03-02 21:02
Yes, that's the update, I guess I only restarted the sublime today, so it
updated today even though the update is of older date.

**Comment by ig0774** [comment] 2016-03-03 15:32
The comment disappeared presumably because it was deleted by its author.

To be clear, does this problem persist after you restart Sublime or can we close this?

If the problem persists, could you provide us the output from your console (**View|Console**) so we can try to figure out what is happening?

Thanks

**Comment by cyrus-** [comment] 2016-03-04 18:05
I'm having the same problem with the latest version. 

I get the following when I try to build in the console:

Unable to find target command: make_pdf

**Comment by ig0774** [comment] 2016-03-04 18:08
Is there anything further up when it should say "Loading LaTeXTools" and especially "Loading LaTeXTools.makePDF.py"? Also what platform are you on?

**Comment by cyrus-** [comment] 2016-03-04 18:19
Hm, I restarted sublime text and the problem went away, so I can't reproduce it at the moment. If it comes up again I'll report back. I'm on Linux.

**Comment by ig0774** [comment] 2016-03-04 19:47
Ah, ok! If goes away after restart, then it's probably nothing to worry about. Occasionally there are glitches caused by trying to update code that's already loaded. Once the app is restarted, the problem should be gone for good.

**Comment by lewaszek** [comment] 2016-03-05 16:52
Having had a similar issue, I noticed that `Unable to find target command: make_pdf` showed up in the console, when LaTeXTools was disabled by Package Control.

**Comment by albertouri** [comment] 2016-03-06 01:10
I got the same error, just after updating. The exact problem was
`ImportError: cannot import name parse_tex_directives`
From getTeXRoot.py line 11
Apparently restarting Sublime fix the problem.

**Comment by tomaskrehlik** [comment] 2016-03-15 08:56
I had to reinstall, but that fixed the problem.

**Comment by ssemigr** [comment] 2016-04-02 16:46
I'm having, perhaps, the same issue since I updated to version 3109 (on Mac). The error I have is 
Traceback (most recent call last):
 File "/Applications/Sublime Text.app/Contents/MacOS/sublime_plugin.py", line 462, in is_enabled_
    raise ValueError("is_enabled must return a bool", self)
Reinstallation didn't help.

**Comment by ssemigr** [comment] 2016-04-02 16:53
Forget it, now it started building, I have no idea why exactly. 
I just tried compiling a tex file which had 
% !TEX program = xelatex
in the header and after it compiled successfully, now it also compiles ordinary LaTeX files.

**Comment by ebarojas** [comment] 2016-04-20 16:29
I had this same problem, it seems the package manager was updated and then I just had to restart...

**Comment by ig0774** [comment] 2016-04-20 17:32
Hopefully with the latest version(s) these errors will go away, but I will be monitoring

**Closed** 2017-01-09 14:26 UTC
Labels: enhancement
